const Main = [
  {
    id: 1,
    name: "Maggi",
    category: "breakfast",
    imgsrc: "images/maggi.jfif",
    price: "Rs 120",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 2,
    name: "Sandwitch",
    category: "breakfast",
    imgsrc: "images/sandwitch.jpg",
    price: "Rs 120",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 3,
    name: "Paneer",
    category: "lunch",
    imgsrc: "images/paneer.jpg",
    price: "Rs 120",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 4,
    name: "Daal Fry",
    category: "lunch",
    imgsrc: "images/dalfry.jpg",
    price: "Rs 120",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 5,
    name: "Chips",
    category: "snacks",
    imgsrc: "images/chips.jpg",
    price: "Rs 120",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 6,
    name: "Thali @ 60",
    category: "dinner",
    imgsrc: "images/thali.jpg",
    price: "Rs 120",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 7,
    name: "Egg Curry",
    category: "dinner",
    imgsrc: "images/eggcurry.jpg",
    price: "Rs 120",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 8,
    name: "Fish Fry",
    category: "dinner",
    imgsrc: "images/fishfry.jpg",
    price: "Rs 120",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 9,
    name: "Chicken Tikka",
    category: "dinner",
    imgsrc: "images/chickentikka.jpg",
    price: "Rs 120",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];

export default Main;
